server:
  port: 8099
  tomcat:
      uri-encoding: UTF-8
      max-connections: 500
      min-spare-threads: 25
      max-threads: 300
      accept-count: 200
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xsy?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC
    username: root
    password: xsy
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.sheep.excel.entity